package enums;

/**
 * Created by Jonathan on 7/12/17.
 */
public enum Skill {
    ATHLETICS,
    ACROBATICS, SLEIGHT_OF_HAND, STEALTH,
    ARCANA, HISTORY, INVESTIGATION, NATURE, RELIGION,
    ANIMAL_HANDLING, INSIGHT, PERCEPTION, SURVIVAL,
    DECEPTION, INTIMIDATION, PERFORMANCE, PERSUASION
}
